-- ============================================================================
-- ACADENO LMS — Lead Management Module Schema (EPIC-02)
-- Migration: 002_leads_schema.sql
-- PostgreSQL 15+
-- ============================================================================

-- ============================================================================
-- 1. ENUMS
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_status') THEN
        CREATE TYPE lead_status AS ENUM (
            'new',
            'contacted',
            'interested',
            'negotiating',
            'converted',
            'cold'
        );
    END IF;
END
$$;

-- ============================================================================
-- 2. TABLES
-- ============================================================================

-- ---------- 2a. leads ----------
CREATE TABLE IF NOT EXISTS leads (
    id                  UUID            PRIMARY KEY DEFAULT uuid_generate_v4(),
    bda_id              UUID            NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    full_name           TEXT            NOT NULL,
    email               TEXT            NOT NULL,
    phone               TEXT            NOT NULL,
    course_interest     TEXT            NOT NULL,
    lead_source         TEXT            NOT NULL,
    status              lead_status     NOT NULL DEFAULT 'new',
    is_locked           BOOLEAN         DEFAULT false,
    follow_up_date      DATE,
    last_activity_at    TIMESTAMPTZ     DEFAULT NOW(),
    created_at          TIMESTAMPTZ     DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     DEFAULT NOW(),

    -- BR-L01: Composite unique constraint preventing duplicates
    CONSTRAINT uq_leads_email_phone UNIQUE (email, phone)
);

COMMENT ON TABLE leads IS 'Stores prospective student leads managed exclusively by Business Development Associates (BDAs).';

-- ---------- 2b. lead_status_history ----------
CREATE TABLE IF NOT EXISTS lead_status_history (
    id                  UUID            PRIMARY KEY DEFAULT uuid_generate_v4(),
    lead_id             UUID            NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    changed_by          UUID            NOT NULL REFERENCES users(id),
    from_status         lead_status,
    to_status           lead_status     NOT NULL,
    reason              TEXT,           -- Required only for retrospective/backward transitions
    changed_at          TIMESTAMPTZ     DEFAULT NOW()
);

COMMENT ON TABLE lead_status_history IS 'Immutable audit ledger mapping the historical lifecycle trajectory of leads.';

-- ---------- 2c. lead_notes ----------
CREATE TABLE IF NOT EXISTS lead_notes (
    id                  UUID            PRIMARY KEY DEFAULT uuid_generate_v4(),
    lead_id             UUID            NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    bda_id              UUID            NOT NULL REFERENCES users(id),
    note_text           TEXT            NOT NULL,
    follow_up_date      DATE,
    created_at          TIMESTAMPTZ     DEFAULT NOW()
    -- Note: updated_at intentionally omitted — notes are strictly append-only (US-BDA-03)
);

COMMENT ON TABLE lead_notes IS 'Append-only chronological notes generated by BDAs tracking customer interaction.';

-- ============================================================================
-- 3. INDEXES
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_leads_bda_id ON leads (bda_id);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads (status);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads (phone);
CREATE INDEX IF NOT EXISTS idx_leads_follow_up_date ON leads (follow_up_date);
CREATE INDEX IF NOT EXISTS idx_lead_notes_lead_id ON lead_notes (lead_id);

-- ============================================================================
-- 4. TRIGGERS
-- ============================================================================
-- Reusing the universal `fn_set_updated_at()` trigger predefined in 001_auth_schema.sql
DROP TRIGGER IF EXISTS trg_leads_updated_at ON leads;
CREATE TRIGGER trg_leads_updated_at
    BEFORE UPDATE ON leads
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- ============================================================================
-- 5. ROW-LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE leads                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_status_history   ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_notes            ENABLE ROW LEVEL SECURITY;

ALTER TABLE leads                 FORCE ROW LEVEL SECURITY;
ALTER TABLE lead_status_history   FORCE ROW LEVEL SECURITY;
ALTER TABLE lead_notes            FORCE ROW LEVEL SECURITY;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- 5a. LEADS RLS POLICIES
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- 1. BDA Operations: Only interact with their assigned rows
CREATE POLICY bda_select_leads ON leads FOR SELECT USING (
    (current_setting('app.current_user_role', TRUE) = 'bda' AND bda_id = current_setting('app.current_user_id', TRUE)::UUID)
);

CREATE POLICY bda_insert_leads ON leads FOR INSERT WITH CHECK (
    (current_setting('app.current_user_role', TRUE) = 'bda' AND bda_id = current_setting('app.current_user_id', TRUE)::UUID)
);

CREATE POLICY bda_update_leads ON leads FOR UPDATE USING (
    (current_setting('app.current_user_role', TRUE) = 'bda' AND bda_id = current_setting('app.current_user_id', TRUE)::UUID)
) WITH CHECK (
    (current_setting('app.current_user_role', TRUE) = 'bda' AND bda_id = current_setting('app.current_user_id', TRUE)::UUID)
);

-- 2. Super Admin & HR: Globals monitoring (SELECT ONLY via direct scope)
CREATE POLICY global_select_leads ON leads FOR SELECT USING (
    current_setting('app.current_user_role', TRUE) IN ('super_admin', 'hr')
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- 5b. LEAD STATUS HISTORY POLICIES
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE POLICY bda_select_history ON lead_status_history FOR SELECT USING (
    current_setting('app.current_user_role', TRUE) = 'bda' 
    AND changed_by = current_setting('app.current_user_id', TRUE)::UUID
);

CREATE POLICY bda_insert_history ON lead_status_history FOR INSERT WITH CHECK (
    current_setting('app.current_user_role', TRUE) = 'bda' 
    AND changed_by = current_setting('app.current_user_id', TRUE)::UUID
);

CREATE POLICY global_select_history ON lead_status_history FOR SELECT USING (
    current_setting('app.current_user_role', TRUE) IN ('super_admin', 'hr')
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- 5c. LEAD NOTES POLICIES
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE POLICY bda_select_notes ON lead_notes FOR SELECT USING (
    current_setting('app.current_user_role', TRUE) = 'bda' 
    AND bda_id = current_setting('app.current_user_id', TRUE)::UUID
);

CREATE POLICY bda_insert_notes ON lead_notes FOR INSERT WITH CHECK (
    current_setting('app.current_user_role', TRUE) = 'bda' 
    AND bda_id = current_setting('app.current_user_id', TRUE)::UUID
);

CREATE POLICY global_select_notes ON lead_notes FOR SELECT USING (
    current_setting('app.current_user_role', TRUE) IN ('super_admin', 'hr')
);

-- ============================================================================
-- 6. PERMISSIONS GUARANTEE
-- ============================================================================
-- Re-affirm Application Client Privileges to circumvent Permission Denied
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lms_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lms_user;
